export { ApiError, createApiClient, type ApiClient, type ApiClientOptions } from "./http";
export {
  checkInContextSchema,
  checkInPropertySchema,
  guestCheckInSubmitInputSchema,
  guestShareListResponseSchema,
  guestShareSchema,
  guestStaySchema,
  hotelIdentityAccessReasonSchema,
  hotelIdentityAccessSchema,
  hotelQrTokenResponseSchema,
  hotelStayDetailSchema,
  hotelStayImageAccessResponseSchema,
  hotelStayListItemSchema,
  hotelStayListQuerySchema,
  hotelStayListResponseSchema,
  identityAccessActionSchema,
  operationalStayStatusSchema,
  roomStatusSchema,
  roomSummarySchema,
  stayRoomSummarySchema,
  sharedCompanionSchema,
  sharedDocumentSchema,
  sharedIdentitySnapshotSchema,
  stayStatusSchema,
  type CheckInContext,
  type CheckInProperty,
  type GuestCheckInSubmitInput,
  type GuestShare,
  type GuestShareListResponse,
  type GuestStay,
  type HotelIdentityAccessReason,
  type HotelQrTokenResponse,
  type HotelStayDetail,
  type HotelStayListItem,
  type HotelStayListQuery,
  type HotelStayListResponse,
  type IdentityAccessAction,
  type OperationalStayStatus,
  type RoomStatus,
  type RoomSummary,
  type StayRoomSummary,
  type SharedIdentitySnapshot,
  type StayStatus,
} from "./check-in";
export {
  hotelGuestListResponseSchema,
  hotelGuestStaySchema,
  hotelReportDateRangeQuerySchema,
  hotelReportInHouseEntrySchema,
  hotelReportInHouseResponseSchema,
  hotelReportOccupancyResponseSchema,
  hotelReportRegisterEntrySchema,
  hotelReportRegisterResponseSchema,
  hotelReportRoomStatusCountsSchema,
  hotelReportStatusCountsResponseSchema,
  hotelReportStayStatusCountsSchema,
  hotelRoomCreateInputSchema,
  hotelRoomListResponseSchema,
  hotelRoomSchema,
  hotelRoomStatusInputSchema,
  hotelStayCheckInInputSchema,
  type HotelGuestListResponse,
  type HotelGuestStay,
  type HotelReportDateRangeQuery,
  type HotelReportInHouseEntry,
  type HotelReportInHouseResponse,
  type HotelReportOccupancyResponse,
  type HotelReportRegisterEntry,
  type HotelReportRegisterResponse,
  type HotelReportRoomStatusCounts,
  type HotelReportStatusCountsResponse,
  type HotelReportStayStatusCounts,
  type HotelRoom,
  type HotelRoomCreateInput,
  type HotelRoomListResponse,
  type HotelRoomStatusInput,
  type HotelStayCheckInInput,
} from "./hotel-operations";
export {
  deleteAccountInputSchema,
  updateAccountInputSchema,
  type DeleteAccountInput,
  type UpdateAccountInput,
} from "./account";
export {
  guestProfileInputSchema,
  guestProfileMissingFieldSchema,
  guestProfileResponseSchema,
  type GuestProfileInput,
  type GuestProfileMissingField,
  type GuestProfileResponse,
} from "./guest-profile";
export {
  identityDocumentImageAccessInputSchema,
  identityDocumentImageAccessResponseSchema,
  identityDocumentImageSchema,
  identityDocumentImageSideSchema,
  identityDocumentInputSchema,
  identityDocumentListResponseSchema,
  identityDocumentMissingFieldSchema,
  identityDocumentSchema,
  identityDocumentTypeSchema,
  identityDocumentUploadFinalizeInputSchema,
  identityDocumentUploadInputSchema,
  identityDocumentUploadResponseSchema,
  type IdentityDocument,
  type IdentityDocumentImageAccessInput,
  type IdentityDocumentImageAccessResponse,
  type IdentityDocumentImageSide,
  type IdentityDocumentInput,
  type IdentityDocumentListResponse,
  type IdentityDocumentMissingField,
  type IdentityDocumentType,
  type IdentityDocumentUploadFinalizeInput,
  type IdentityDocumentUploadInput,
  type IdentityDocumentUploadResponse,
} from "./identity-document";
export {
  companionProfileInputSchema,
  companionProfileListResponseSchema,
  companionProfileMissingFieldSchema,
  companionProfileSchema,
  type CompanionProfile,
  type CompanionProfileInput,
  type CompanionProfileListResponse,
  type CompanionProfileMissingField,
} from "./companion-profile";
export {
  createExampleProjectInputSchema,
  exampleProjectIdParamsSchema,
  exampleProjectListSchema,
  exampleProjectSchema,
  updateExampleProjectInputSchema,
  type CreateExampleProjectInput,
  type ExampleProject,
  type ExampleProjectIdParams,
  type ExampleProjectList,
  type UpdateExampleProjectInput,
} from "./example-projects";
export {
  apiErrorResponseSchema,
  meResponseSchema,
  membershipRoleSchema,
  membershipSchema,
  organizationSummarySchema,
  permissionSchema,
  platformRoleSchema,
  propertyAccessSchema,
  type MeResponse,
  type Membership,
  type MembershipRole,
  type Permission,
  type PlatformRole,
} from "./me";
export {
  platformAuditActionSchema,
  platformMemberAddInputSchema,
  platformMemberSchema,
  platformMemberUpdateInputSchema,
  platformMembershipRoleSchema,
  platformOrganizationDetailSchema,
  platformOrganizationListResponseSchema,
  platformOrganizationOnboardingInputSchema,
  platformOrganizationOnboardingResponseSchema,
  platformOrganizationSummarySchema,
  platformOversightAuditEntrySchema,
  platformOversightAuditQuerySchema,
  platformOversightAuditResponseSchema,
  platformOversightIdentityAuditEntrySchema,
  platformOversightPlatformAuditEntrySchema,
  platformOversightPropertyStaysSchema,
  platformOversightStatusCountsSchema,
  platformOversightStaysResponseSchema,
  platformPropertyCreateInputSchema,
  platformPropertySchema,
  platformUserSearchParamsSchema,
  platformUserSearchResponseSchema,
  platformUserSearchResultSchema,
  type PlatformAuditAction,
  type PlatformMember,
  type PlatformMemberAddInput,
  type PlatformMemberUpdateInput,
  type PlatformMembershipRole,
  type PlatformOrganizationDetail,
  type PlatformOrganizationListResponse,
  type PlatformOrganizationOnboardingInput,
  type PlatformOrganizationOnboardingResponse,
  type PlatformOrganizationSummary,
  type PlatformOversightAuditEntry,
  type PlatformOversightAuditQuery,
  type PlatformOversightAuditResponse,
  type PlatformOversightIdentityAuditEntry,
  type PlatformOversightPlatformAuditEntry,
  type PlatformOversightPropertyStays,
  type PlatformOversightStaysResponse,
  type PlatformOversightStatusCounts,
  type PlatformProperty,
  type PlatformPropertyCreateInput,
  type PlatformUserSearchParams,
  type PlatformUserSearchResponse,
  type PlatformUserSearchResult,
} from "./platform";
