import type { HotelGuestStay } from "@tattvix/contracts";
import { Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { History, UserRound } from "lucide-react";
import { EmptyState, Kpi, KpiStrip, PageHeader, Panel, PanelHeader, StatusPill } from "@/components/design-system";
import { getInitials } from "@/lib/initials";
import { hotelOperationsQueries } from "../queries";

export function HotelGuestsPage({ organizationSlug, propertySlug }: { organizationSlug: string; propertySlug: string; propertyName: string }) {
  const { data } = useSuspenseQuery(hotelOperationsQueries.guests(organizationSlug, propertySlug));
  return <div className="mx-auto grid max-w-[1400px] gap-6"><PageHeader title="Guests" /><KpiStrip><Kpi icon={UserRound} label="In house" value={data.current.length} /><Kpi icon={History} label="Stay history" value={data.history.length} /><Kpi icon={UserRound} label="With companions" value={[...data.current, ...data.history].filter((stay) => stay.companionCount > 0).length} /></KpiStrip><GuestSection title="Current guests" icon={UserRound} stays={data.current} organizationSlug={organizationSlug} propertySlug={propertySlug} empty="No guests are currently checked in." /><GuestSection title="Stay history" icon={History} stays={data.history} organizationSlug={organizationSlug} propertySlug={propertySlug} empty="Completed stays will appear here after checkout." /></div>;
}
function GuestSection({ title, icon, stays, organizationSlug, propertySlug, empty }: { title: string; icon: typeof UserRound; stays: HotelGuestStay[]; organizationSlug: string; propertySlug: string; empty: string }) { return <Panel><PanelHeader title={title} icon={icon} meta={stays.length} />{stays.length ? <div>{stays.map((stay) => <GuestRow key={stay.id} stay={stay} organizationSlug={organizationSlug} propertySlug={propertySlug} />)}</div> : <EmptyState icon={icon} title="Nothing here yet" description={empty} />}</Panel>; }
function GuestRow({ stay, organizationSlug, propertySlug }: { stay: HotelGuestStay; organizationSlug: string; propertySlug: string }) { const referenceTime = stay.operationalStatus === "CHECKED_IN" ? stay.checkedInAt : stay.checkedOutAt; return <Link to="/hotel/$organizationSlug/$propertySlug/stays/$stayId" params={{ organizationSlug, propertySlug, stayId: stay.id }} className="flex min-h-11 items-center gap-3 border-t border-border-soft px-5 py-2 hover:bg-muted/50"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-muted text-xs font-semibold">{getInitials(stay.guestName)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="truncate text-sm font-medium">{stay.guestName}</span><StatusPill tone={stay.operationalStatus === "CHECKED_IN" ? "success" : "neutral"}>{stay.operationalStatus === "CHECKED_IN" ? "Checked in" : "Checked out"}</StatusPill></div><p className="text-xs text-subtle-foreground">{stay.room ? `Room ${stay.room.number} · ` : ""}{stay.companionCount > 0 ? `+${stay.companionCount} · ` : ""}{stay.operationalStatus === "CHECKED_IN" ? "Checked in" : "Checked out"} {referenceTime ? formatDateTime(referenceTime) : "—"}</p></div></Link>; }
function formatDateTime(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
