# Generated by Django 5.2.15 on 2026-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('public_metadata', models.JSONField(blank=True, default=dict)),
                ('private_metadata', models.JSONField(blank=True, default=dict)),
                ('unsafe_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_synced_at'], name='api_clerkus_last_sy_654277_idx')],
            },
        ),
    ]
