# Generated by Django 5.2.15 on 2026-07-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_membership_platformroleassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_first_name', models.CharField(blank=True, default='', max_length=150)),
                ('legal_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=2)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state_region', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='api.clerkuser')),
            ],
        ),
    ]
