# Generated by Django 5.2.15 on 2026-07-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guestprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_first_name', models.CharField(blank=True, default='', max_length=150)),
                ('legal_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('nationality', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_profiles', to='api.clerkuser')),
            ],
        ),
    ]
