# Generated by Django 5.2.15 on 2026-07-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companionprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar'), ('PASSPORT', 'Passport'), ('DRIVING_LICENCE', 'Driving licence'), ('VOTER_ID', 'Voter ID')], default='', max_length=32)),
                ('document_number', models.CharField(blank=True, default='', max_length=64)),
                ('name_on_document', models.CharField(blank=True, default='', max_length=300)),
                ('issuing_country', models.CharField(blank=True, default='', max_length=2)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='api.clerkuser')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IdentityDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back')], max_length=8)),
                ('object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('content_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pending_object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('pending_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('pending_content_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.identitydocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'side'), name='unique_identity_document_image_side')],
            },
        ),
    ]
