# Generated by Django 5.2.15 on 2026-07-18 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_identitydocument_identitydocumentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelQrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('token_hint', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hotel_qr_tokens', to='api.clerkuser')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_tokens', to='api.property')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to hotel'), ('CLOSED', 'Closed'), ('REVOKED', 'Consent revoked')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('hotel_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_stays', to='api.clerkuser')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='api.property')),
                ('qr_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='api.hotelqrtoken')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SharedIdentitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_data', models.JSONField()),
                ('companion_data', models.JSONField(default=list)),
                ('document_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_snapshot', to='api.stay')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DETAILS_VIEWED', 'Identity details viewed'), ('DOCUMENT_VIEWED', 'Document image viewed'), ('STAY_CLOSED', 'Stay closed'), ('CONSENT_REVOKED', 'Consent revoked')], max_length=32)),
                ('image_side', models.CharField(blank=True, choices=[('FRONT', 'Front'), ('BACK', 'Back')], default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_access_events', to='api.clerkuser')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_access_events', to='api.stay')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(max_length=32)),
                ('data_categories', models.JSONField(default=list)),
                ('granted_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_consent_grants', to='api.clerkuser')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_grant', to='api.stay')),
            ],
        ),
        migrations.CreateModel(
            name='SharedIdentityDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back')], max_length=8)),
                ('object_key', models.CharField(max_length=1024)),
                ('content_type', models.CharField(max_length=100)),
                ('content_length', models.PositiveBigIntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_images', to='api.sharedidentitysnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'side'), name='unique_shared_identity_image_side')],
            },
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('guest', 'qr_token'), name='unique_draft_stay_per_guest_qr'),
        ),
    ]
