# Generated by Django 5.2.15 on 2026-07-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0006_hotelqrtoken_stay_sharedidentitysnapshot_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="SET lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='stay',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='operational_status',
            field=models.CharField(choices=[('PENDING_CHECK_IN', 'Pending check-in'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out')], db_default='PENDING_CHECK_IN', default='PENDING_CHECK_IN', max_length=24),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('floor', models.CharField(blank=True, default='', max_length=32)),
                ('room_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], default='VACANT', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='api.property')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='api.room'),
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "api_stay" '
                'ADD CONSTRAINT "api_stay_room_id_fk" '
                'FOREIGN KEY ("room_id") REFERENCES "api_room" ("id") '
                'ON DELETE NO ACTION NOT VALID;'
            ),
            reverse_sql=(
                'ALTER TABLE "api_stay" '
                'DROP CONSTRAINT IF EXISTS "api_stay_room_id_fk";'
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE UNIQUE INDEX CONCURRENTLY '
                        '"unique_checked_in_stay_per_room" '
                        'ON "api_stay" ("room_id") '
                        "WHERE \"operational_status\" = 'CHECKED_IN';"
                    ),
                    reverse_sql=(
                        'DROP INDEX CONCURRENTLY IF EXISTS '
                        '"unique_checked_in_stay_per_room";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='stay',
                    constraint=models.UniqueConstraint(condition=models.Q(('operational_status', 'CHECKED_IN')), fields=('room',), name='unique_checked_in_stay_per_room'),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'number'), name='unique_room_number_per_property'),
        ),
        migrations.RunSQL(
            sql="RESET lock_timeout;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
