# Generated by Django 5.2.15 on 2026-08-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_validate_stay_room_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROPERTY_CREATED', 'Property created'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_ROLE_CHANGED', 'Member role changed'), ('MEMBER_DEACTIVATED', 'Member deactivated'), ('MEMBER_REACTIVATED', 'Member reactivated')], max_length=32)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_events', to='api.clerkuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_events', to='api.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
