# Generated by Django 5.2.15 on 2026-10-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_platformauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityaccessaudit",
            name="companion_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RemoveConstraint(
            model_name="sharedidentitydocumentimage",
            name="unique_shared_identity_image_side",
        ),
        migrations.AddField(
            model_name="identitydocument",
            name="companion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_documents",
                to="api.companionprofile",
            ),
        ),
        migrations.AddField(
            model_name="sharedidentitydocumentimage",
            name="companion_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="sharedidentitydocumentimage",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "companion_id", "side"),
                name="unique_shared_identity_participant_side",
            ),
        ),
    ]
