# Generated by Django 5.2.15 on 2026-10-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_companion_identity_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=1000)),
                ("contact_phone", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hotel_requests",
                        to="api.clerkuser",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.property",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_hotel_requests",
                        to="api.clerkuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="hotel_request_queue_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("applicant",),
                        name="one_pending_hotel_request",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("organization__isnull", True),
                                ("property__isnull", True),
                                ("rejection_reason", ""),
                                ("reviewed_at__isnull", True),
                                ("reviewer__isnull", True),
                                ("status", "PENDING"),
                            ),
                            models.Q(
                                ("organization__isnull", False),
                                ("property__isnull", False),
                                ("rejection_reason", ""),
                                ("reviewed_at__isnull", False),
                                ("reviewer__isnull", False),
                                ("status", "APPROVED"),
                            ),
                            models.Q(
                                ("organization__isnull", True),
                                ("property__isnull", True),
                                ("reviewed_at__isnull", False),
                                ("reviewer__isnull", False),
                                ("status", "REJECTED"),
                                models.Q(("rejection_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="hotel_request_review_state",
                    ),
                ],
            },
        ),
    ]
