# Generated by Django 5.2.15 on 2026-10-03 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_approved_registration_details(apps, schema_editor):
    Registration = apps.get_model("api", "HotelRegistrationRequest")
    Property = apps.get_model("api", "Property")
    for registration in Registration.objects.filter(
        property_id__isnull=False
    ).iterator():
        Property.objects.filter(pk=registration.property_id).update(
            address=registration.address, contact_phone=registration.contact_phone
        )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_hotel_registration_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="StayCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ROOM", "Room"), ("EXTRA", "Extra")], max_length=5
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_minor", models.PositiveIntegerField()),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="check_in_time",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="property",
            name="check_out_time",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="property",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="room",
            name="nightly_rate_minor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stay",
            name="billing_nights",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stay",
            name="nightly_rate_minor",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(("nightly_rate_minor__lte", 100000000)),
                name="room_rate_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="stay",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("billing_nights__gte", 1), ("billing_nights__lte", 365)
                ),
                name="stay_billing_nights_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="stay",
            constraint=models.CheckConstraint(
                condition=models.Q(("nightly_rate_minor__lte", 100000000)),
                name="stay_rate_limit",
            ),
        ),
        migrations.AddField(
            model_name="staycharge",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_stay_charges",
                to="api.clerkuser",
            ),
        ),
        migrations.AddField(
            model_name="staycharge",
            name="stay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charges",
                to="api.stay",
            ),
        ),
        migrations.AddField(
            model_name="staycharge",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_stay_charges",
                to="api.clerkuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.UniqueConstraint(
                fields=("stay", "request_id"), name="unique_stay_charge_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "ROOM")),
                fields=("stay",),
                name="unique_stay_room_charge",
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 9999)),
                name="charge_quantity_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price_minor__lte", 100000000)),
                name="charge_price_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["ROOM", "EXTRA"])),
                name="charge_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="staycharge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                    ),
                    models.Q(
                        ("kind", "EXTRA"),
                        ("voided_at__isnull", False),
                        ("voided_by__isnull", False),
                        models.Q(("void_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="charge_void_audit_consistent",
            ),
        ),
        migrations.RunPython(
            copy_approved_registration_details, migrations.RunPython.noop
        ),
    ]
