# Generated by Django 5.2.15 on 2026-10-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_stay_billing_and_property_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COVER', 'Cover'), ('ROOM_TYPE', 'Room type')], max_length=10)),
                ('room_type', models.CharField(blank=True, default='', max_length=100)),
                ('object_key', models.CharField(blank=True, default='', max_length=512)),
                ('pending_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('pending_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('pending_content_length', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'kind', 'room_type'), name='unique_property_photo_slot')],
            },
        ),
    ]
